First Version
RitwikSingh28/GitHubPrac pull request #14
Opened 2022-12-18 09:35 UTC by jaspal007

I have created a prototype for a login app

2022-12-18 10:05 UTC, RitwikSingh28 requested changes
@jaspal007 
Delete the .git folder (hidden) in your machine's remote repo, and then try to push the changes to this PR. 
You need to make sure that your project folder is not a git repository in itself. As the outer folder is already a git repo. Do look after it and make changes accordingly.

2022-12-25 23:49 UTC, jaspal007 commented
> @jaspal007 Delete the .git folder (hidden) in your machine's remote repo, and then try to push the changes to this PR. You need to make sure that your project folder is not a git repository in itself. As the outer folder is already a git repo. Do look after it and make changes accordingly.

I have reviewed my file on my local machine and performed the task as stated.

2022-12-27 09:26 UTC, jaspal007 commented
Reopening my closed PR

2023-01-04 13:04 UTC, RitwikSingh28 commented on prac2-pages/Jaspal/login.dart
> +      required this.selectHandler,
This method of delegating calls to the parent is actually quite a nice touch! It follows good software design principles, (separation of concerns)... :sunglasses:

2023-01-04 13:24 UTC, RitwikSingh28 requested changes
Great work so far @jaspal007 !! 

Please implement the fixes to the aforementioned issues, and then push the fixes with subsequent commits.

**Note**: Try to fix one issue in a single commit. Results in better readability and version control.

2023-01-04 13:24 UTC, RitwikSingh28 commented on prac2-pages/Jaspal/login.dart
> +                    onPressed: () => 3,
You can try to perform the following tasks here:

- Perform form validation (basic check if they are empty or email contains @)
- If passed, redirect the user to the second page.
- Try to learn about Navigation in Flutter, and use that to route the user to a different page

2023-01-04 13:24 UTC, RitwikSingh28 commented on prac2-pages/Jaspal/main.dart
> +          child: (_tap == false)
This method is creative, but will result in a lot of overhead in performance. For routing between the pages, it is advisable to use **Navigation**. 
Kindly remove this and try to implement page routing here.

2023-01-04 13:24 UTC, RitwikSingh28 commented on prac2-pages/Jaspal/main.dart
> +              ? Column(
**main.dart file should only contain the logic for deciding the initial screens**. The pages to be displayed should be decided here, and not their implementations. :information_source: 

Kindly refactor this into a widget, and put it in a separate file. And then provide its instance here. :thinking: 

Makes the code readable and easily maintainable. :thought_balloon:

2023-01-14 11:42 UTC, jaspal007 commented on prac2-pages/Jaspal/login.dart
> +                    onPressed: () => 3,
Recreated the login widget with form validation

2023-01-14 11:44 UTC, jaspal007 commented on prac2-pages/Jaspal/main.dart
> +          child: (_tap == false)
Rebuilt the app with navigator that uses context stack

2023-01-14 11:45 UTC, jaspal007 commented on prac2-pages/Jaspal/main.dart
> +              ? Column(
Refactored the main.dart to only contain the reference to the home screen and the MaterialApp

2023-01-14 13:20 UTC, RitwikSingh28 commented on prac2-pages/Jaspal/login.dart
> +                    onPressed: () => 3,
Perfectly done! We will be using regex a lot in our upcoming projects!

2023-01-14 13:21 UTC, RitwikSingh28 commented on prac2-pages/Jaspal/main.dart
> +              ? Column(
Resolved! :+1:

2023-01-14 13:24 UTC, RitwikSingh28 requested changes
Everything is perfect @jaspal007 ! 

One other improvement that I would like you to now make is to make the UI adaptive on different mobile displays. Since the values in px are specified as per your test screen, there is a chance that the UI might overflow in other screens.

*Hint* :thought_balloon: 
Look up ScreenUtil package in Flutter

2023-01-14 13:24 UTC, RitwikSingh28 commented on prac2-pages/Jaspal/main.dart
> +          child: (_tap == false)
Resolved

2023-01-17 03:33 UTC, RitwikSingh28 approved these changes
Fantastic @jaspal007 :100: 

Everything is working perfectly, and all the improvements requested have been made. 
I hope with this task, you got a feel of how it looks like to contribute to an open-source project. :smile: 

Merging your PR :+1:

2023-01-17 03:33 UTC, merged